### ISSUE TITLE
week 05 - day 01 - mineswept

### ISSUE THREAD

**Issue by mdewey** [LivCunningham/assignments#17]
# A mine!

This morning we did a couple of code reviews. Take these lessons and finish up your minesweeper apps. 

Also, we have been exploring react for the past week. Let's take those skills and upgrade some old projects. 

## Objectives

- With your new knowledge, finish minesweeper
- Update an old project using React. 

### Explorer Mode

- [ ] Finish your minesweeper
- [ ] Go back to project to a project unit-i (week 1 through 3)

### Adventure Mode

- [ ] Work on any previous adventure or epic mode of any previous homework
- [ ] Go back and redo an old project.

**Comment by LivCunningham** [comment]
BlackJack in REACT:
this is just the beginning player hand and initial deal functionality 👍 
https://github.com/LivCunningham/blkjk-react.git

MineSweeper:
Was really focused on blackjack so I didn't make that much more strides on Minesweeper - I fix the "col" syntax error, so the bombs, clicks, and flags work in the correct places. I haven't really worked on styling or win or loose messaging at all. I will add this. I did add a reset button though! 
https://github.com/LivCunningham/minesweeper

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a60036409d53f8b1c2804766f540dccb4215ec74/giphy-3.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/68)**__
