### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [LivCunningham/assignments#21]
Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [x] Portfolio link

## Summary 
- [x]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [x]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [x]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [x]  Simply write where you went college and your degree.
- [x]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [x]  Upload or submit a link to your resume for review.

**Comment by LivCunningham** [comment]
[Resume_Cunningham2019_Fullstack.pdf](https://github.com/LivCunningham/assignments/files/3323253/Resume_Cunningham2019_Fullstack.pdf)

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6653a5b4c8e877384d759556a53bfc97521ca49f/giphy-17.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/82)**__
