### ISSUE TITLE
week 06 - day 03 - spit and polish 

### ISSUE THREAD

**Issue by mdewey** [LivCunningham/assignments#23]
# Spit and Polish

Your GitHub repository will be part of your portfolio and you will likely link to it from your portfolio.

Creating a clean looking README is as important for a project as having nice clean code.

Here are some examples of great READMEs:

- https://github.com/axios/axios
- https://github.com/Microsoft/vscode
- https://github.com/twbs/bootstrap
- https://github.com/electron/electron

Here are some example of great student READMEs:

- https://github.com/cfsanderson/Minesweeper
- https://github.com/m1g/tic-react-toe
- https://github.com/m1g/snowman

## Objectives

- Create quality readmes

### Explorer Mode

- [x] Choose several (at least three) repositories to update the READMEs
- [x] Include a description, in your own words, of what the assignment was
- [ ] Include a list of technologies (and links to the homepage for each) you used
- [x] Include a link to the project in production (netlify, etc.)
- [x] Include a screenshot or an animated gif (see [Kap](https://github.com/wulkano/kap), [Recordit](http://recordit.co/), or [Licecap](https://www.cockos.com/licecap/))
- Optional:
  - [ ] Include an aspect you are particularly proud of
  - [ ] Include a snippet of code you are proud of (see GitHub Markdown on how to format code snippets)

### Adventure Mode
- [ ] Start working on your resume
- [ ] Go back and do any outstanding homework
- [ ] Go back and do an adventure mode or epic mode that you never got around to

### Epic mode
- [ ] Capstones are going to be coming sooner rather than later. Check out [this resource](https://suncoast.io/handbook/curriculum/final-project/project-ideas/) To help get you started.

**Comment by LivCunningham** [comment]
https://github.com/LivCunningham/minesweeper
https://github.com/LivCunningham/colorama-hooks
https://github.com/LivCunningham/cryptoticker

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74dc376b990fefa4b57db26c0337e9d122b96fd7/giphy-16.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/81)**__
