### ISSUE TITLE
capstone 02 - let's get visual

### ISSUE THREAD

**Issue by mdewey** [LivCunningham/assignments#31]
# Let's get visual!

With the wireframes created, we need to start breathing life into our application. The next step would be to create HTML & CSS. This is the next step because, remember, it all comes down to HTML. This is what the user sees

_NOTE_: Really take advantage of this weekend to get make progress on your capstone. Like the last 7 weeks, the next 5 weeks will go by _fast_.

## Objectives

- Create the HTML and CSS for the final project

## Requirements

- Using `app-app`, start implementing your HTML

### Explorer Mode

- [ ] Create the HTML and CSS version of your wireframes. Stay as true as possible. This should focus on static HTML and CSS.

**Comment by LivCunningham** [comment]
https://github.com/LivCunningham/date-genie.git

Working on linking pages

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3c87e39487e11776789d2fa19615334abd2e3aab/giphy-1.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/66)**__
